
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - react-with-keycloak-by-ella

on:
  push:
    branches:
      - deploy-branch
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge Branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "mariellapulmaoira@gmail.com"
          
          # Fetch the latest changes from main
          git fetch origin main:main

          git merge --allow-unrelated-histories <deploy-branch>
          git rebase main deploy-branch
          git merge --no-ff deploy-branch

          # Merge the feature branch into main
          git checkout main
          git merge "${GITHUB_REF#refs/heads/}"
          
          # Push the merged changes back to main
          git push origin main
          
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm install keycloak-js
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npm install deploy-branch --save-dev
          npm run build --if-present
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Change this to your build directory
